name: DiscussionForum database migrations

permissions:
  id-token: write
  contents: read
  
on:
  push:
    paths: 
      - '.github/workflows/migrations.yml'
      - 'DiscussionForum.Core/Migrations/**'
    branches: 
      [ main ]

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  deploy-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy the Database Changes
        run: |
            ip=$(curl -s https://api.ipify.org/)
            echo $ip
            az sql server firewall-rule create -n allow-github-migrate -g ${{ secrets.AZURE_RG }} -s ${{ vars.SQL_SERVER_NAME }} --start-ip-address $ip --end-ip-address $ip
            dotnet tool install --global dotnet-ef
            cd DiscussionForum.Core
            dotnet ef migrations bundle --self-contained --verbose
            ./efbundle --connection "${{ secrets.SQL_CONNECTIONSTRING }}" --verbose
            az sql server firewall-rule delete -n allow-github-migrate -g ${{ secrets.AZURE_RG }} -s ${{ vars.SQL_SERVER_NAME }}



