name: DiscussionForum database migrations

permissions:
  id-token: write
  contents: read
  
on:
  push:
    paths: 
      - '.github/workflows/migrations.yml'
      - 'DiscussionForum.Core/Migrations/**'
    branches: 
      [ main ]

  workflow_dispatch:
      
jobs:
  deploy-migration:
    runs-on: ubuntu-latest
    env:
        SQL_SERVER_NAME: sql-discussionforum
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set runner IP variable
        run: |
            echo "ip=$(curl -s https://api.ipify.org/)" >> $GITHUB_ENV

      - name: Add firewall rule
        run: |
            az sql server update -g ${{ secrets.AZURE_RG }} -n $SQL_SERVER_NAME -e true
            az sql server firewall-rule create -n allow-github-migrate -g ${{ secrets.AZURE_RG }} -s $SQL_SERVER_NAME --start-ip-address $ip --end-ip-address $ip

      - name: Deploy the Database Changes
        run: |
            dotnet tool install --global dotnet-ef
            cd DiscussionForum.Core
            dotnet ef migrations bundle --self-contained --verbose
            ./efbundle --connection "${{ secrets.SQL_CONNECTIONSTRING }}" --verbose

      - name: Remove firewall rule
        if: always()
        run: |
            az sql server firewall-rule delete -n allow-github-migrate -g ${{ secrets.AZURE_RG }} -s $SQL_SERVER_NAME
            az sql server update -g ${{ secrets.AZURE_RG }} -n $SQL_SERVER_NAME -e false



